name: 'Test Python Code & Code Coverage Upload'
description: 'Runs pytest, creates a coverage report and uploads it to code coverage.'
inputs:
  test-type:
    description: 'integtest if integration test shall be run'
    required: false
    default: 'not integtest'
  package:
    description: 'Name of the python package to be tested.'
    required: true
  token:
    description: 'Codecov secret'
    required: true
runs:
  using: composite
  steps:
    - name: Pytest
      shell: bash
      run: 'poetry run python -m pytest -m "${{ inputs.test-type }}" --cov=${{ inputs.package }} --cov-report=xml --cov-config=.coveragerc'

    - name: Upload to codecoverage
      uses: codecov/codecov-action@v4
      env:
        TOKEN: ${{ inputs.token }}
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        token: ${{ env.TOKEN }}
