name: 'Create Git Tags'
description: 'Creates Git Tags, can replace existing tags'
inputs:
  owner:
    description: 'Owner'
    required: false
    default: ''
  repo:
    description: 'Repository'
    required: false
    default: ''
  tag:
    description: 'Tag'
    required: true
  sha:
    description: 'SHA'
    required: false
    default: ''
  replace:
    description: 'Replace existing Tag'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: 'Create tag ${{ inputs.tag }}'
      uses: actions/github-script@v7
      with:
        script: |
          try {
            const owner = '${{ inputs.owner }}' || context.repo.owner;
            const repo = '${{ inputs.repo }}' || context.repo.repo;
            const tag = '${{ inputs.tag }}';
            const sha = '${{ inputs.sha }}' || context.sha;
            const replace = /^true$/i.test('${{ inputs.replace }}');

            const { data: tags } = await github.rest.git.listMatchingRefs({
              owner: owner,
              repo: repo,
              ref: `tags/${tag}`
            });
            const existing = tags.some(existingTag => existingTag.ref === `refs/tags/${tag}`);

            if (existing) {
              if (!replace) {
                core.setFailed(`Given tag ${tag} already exists`);
                return;
              }

              core.info(`Given tag ${tag} already exists, updating...`);
              await github.rest.git.updateRef({
                owner: owner,
                repo: repo,
                ref: `tags/${tag}`,
                sha: sha
              });
            } else {
              core.info(`Creating new tag ${tag}.`);
              await github.rest.git.createRef({
                owner: owner,
                repo: repo,
                ref: `refs/tags/${tag}`,
                sha: sha
              });
            }
          } catch (err) {
            core.setFailed(`Action failed with error ${err}`);
          }
