name: 'Create Git Tags'
description: 'Creates Git Tags, can replace existing tags'
inputs:
  owner:
    description: 'Owner'
    required: false
    default: ''
  repo:
    description: 'Repository'
    required: false
    default: ''
  tag:
    description: 'Tag'
    required: true
  sha:
    description: 'SHA'
    required: true
  replace:
    description: 'Replace existing Tag'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: 'Create tag ${{ inputs.tag }}'
      uses: actions/github-script@v6
      with:
        script: |
          try {
            const owner = '${{ inputs.owner }}' || context.repo.owner;
            const repo = '${{ inputs.repo }}' || context.repo.repo;
            const tag = '${{ inputs.tag }}';
            const sha = '${{ inputs.sha }}';
            const replace = /^true$/i.test('${{ inputs.replace }}');

            const foo = await github.rest.git.getRef({
              owner: owner,
              repo: repo,
              ref: `tags/${tag}`
            });
            if (foo.status !== 200) {
              core.setFailed(`listMatchingRefs response: ${JSON.stringify(foo)}`);
              return;
            }

            const response = await github.rest.git.listMatchingRefs({
              owner: owner,
              repo: repo,
              ref: `tags/faosdoadomakndsajklb`
            });
            if (response.status !== 200) {
              core.setFailed(`listMatchingRefs response: ${JSON.stringify(response)}`);
              return;
            }
            const existing = response.data.some(existingTag => existingTag === `refs/tags/${tag}`);

            if (existing) {
              if (!replace) {
                core.setFailed(`Given tag ${tag} already exists`);
                return;
              }
              
              const result = await github.rest.git.updateRef({
                owner: owner,
                repo: repo,
                ref: `tags/${tag}`,
                sha: sha
              });
              if (result.status !== 200) {
                core.setFailed(`updateRef response: ${JSON.stringify(result)}`);
                return;
              }
            } else {
              const result = await github.rest.git.createRef({
                owner: owner,
                repo: repo,
                ref: `refs/tags/${tag}`,
                sha: sha
              });
              if (result.status !== 200) {
                core.setFailed(`createRef response: ${JSON.stringify(result)}`);
                return;
              }
            }
          } catch (err) {
            core.setFailed(`Action failed with error ${err}`);
            return;
          }
