name: Add semver tags on release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  apply-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Create tags'
        id: version
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const version = context.ref.substring('refs/tags/v'.length);
              const [major, minor, patch] = version.split('.');
              const version = {
                major: major,
                minor: minor,
                patch: patch
              };
            
              core.info(`Version: ${version}`);
            
              for (const [key, value] of Object.entries(version)) {
                core.setOutputs(key, value);
              }
            } catch (err) {
              core.setFailed(`Action failed with error ${err}`);
            }

      - uses: actions/github-script@v6
        name: 'Create tags'
        with:
          script: |
            try {
              /*github.rest.git.createRef({
                owner: '${{ github.repository_owner }}',
                repo: '${{ github.repository }}',
                ref: 'refs/tags/v${{ steps.version.outputs.major }}',
                sha: '${{ github.sha }}'
              });
              github.rest.git.createRef({
                owner: '${{ github.repository_owner }}',
                repo: '${{ github.repository }}',
                ref: 'refs/tags/v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}',
                sha: '${{ github.sha }}'
              });*/
              core.info('v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}');
            } catch (err) {
              core.setFailed(`Action failed with error ${err}`);
            }
