name: 'Add semver tags on release'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  apply-tags:
    runs-on: ubuntu-latest
    steps:
      - name: 'Extract version info'
        id: version
        uses: Whist-Team/actions/extract-semver@v2

      - name: 'Create major tag'
        uses: Whist-Team/actions/create-tag@v2
        with:
          tag: 'v${{ steps.version.outputs.major }}'
          replace: true

      - name: 'Create major.minor tag'
        uses: Whist-Team/actions/create-tag@v2
        with:
          tag: 'v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}'
          replace: true
