name: 'Add semver tags on release'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  apply-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Extract version info'
        id: version
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const version = context.ref.substring('refs/tags/v'.length);
              const [major, minor, patch] = version.split('.');
              const semver = {
                major: major,
                minor: minor,
                patch: patch
              };
            
              core.info(`Version: ${JSON.stringify(semver)}`);
            
              for (const [key, value] of Object.entries(semver)) {
                core.setOutput(key, value);
              }
            } catch (err) {
              core.setFailed(`Action failed with error ${err}`);
            }

      - name: 'Create tags'
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const major = ${{ steps.version.outputs.major }};
              const minor = ${{ steps.version.outputs.minor }};
              const patch = ${{ steps.version.outputs.patch }};
              const {owner, repo} = context.repo;
              github.rest.git.createRef({
                owner: owner,
                repo: repo,
                ref: `refs/tags/v${major}`,
                sha: context.sha
              });
              github.rest.git.createRef({
                owner: owner,
                repo: repo,
                ref: `refs/tags/v${major}.${minor}`,
                sha: context.sha
              });
            } catch (err) {
              core.setFailed(`Action failed with error ${err}`);
            }
