name: 'Add semver tags on release'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  apply-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Extract version info'
        id: version
        uses: ./extract-semver

      - name: 'Create major tag'
        uses: ./create-tag
        with:
          tag: 'v${{ steps.version.outputs.major }}'
          replace: true

      - name: 'Create major.minor tag'
        uses: ./create-tag
        with:
          tag: 'v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}'
          replace: true
